DROP DATABASE IF EXISTS test_post;

CREATE TABLE IF NOT EXISTS user(
    id SERIAL PRIMARY KEY,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    email     VARCHAR(200) NOT NULL,
    password CHAR(60) NOT NULL
)